name: Build aapt2

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Reason'     
        required: false
        default: 'Update package'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target_arch: [x86_64, arm64]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Setup cosmo toolchain
        uses: bjia56/setup-cosmocc@v0.0.3

      - run: ./patch.sh
      - run: ./build.sh ${{ matrix.target_arch }}
        env:
          NDK_TOOLCHAIN: ${{ runner.temp }}/cosmocc-4.0.2

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.target_arch }}
          path: dist
